name: Acceptance Smoke

on:
  push:
    branches: [ dev, ci/acceptance-smoke ]
  pull_request:
    branches: [ dev ]

jobs:
  acceptance-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run acceptance smoke (LOG_MCP=1)
        id: acceptance
        env:
          LOG_MCP: '1'
          LOG_DIR: 'mcp-starter/logs'
        run: |
          mkdir -p mcp-starter/logs
          npm run acceptance || exit 1

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-logs
          path: mcp-starter/logs/**
