name: Acceptance Smoke

on:
  push:
    branches: [ dev, ci/acceptance-smoke ]
  pull_request:
    branches: [ dev ]

jobs:
  acceptance-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (spellbook-mcp:ci)
        run: |
          docker build --file Dockerfile.mcp -t spellbook-mcp:ci .

      - name: Run acceptance smoke inside Docker
        id: acceptance
        env:
          LOG_MCP: '1'
          LOG_DIR: '/app/mcp-starter/logs'
        run: |
          set -euo pipefail
          # Ensure logs dir exists on host
          mkdir -p mcp-starter/logs

          # Create container using --entrypoint /bin/sh and run the acceptance command via -c
          CONTAINER_ID=$(docker create --entrypoint '/bin/sh' -e LOG_MCP=1 -e LOG_DIR=/app/mcp-starter/logs spellbook-mcp:ci -c "cd /app && npm --prefix /app/mcp-starter ci --omit=dev && cd /app && npm run acceptance")
          echo "Created container: $CONTAINER_ID"

          # Start container and stream output (so we capture test console output in the job log)
          docker start -a "$CONTAINER_ID" || true

          # Copy logs out of container to host workspace for artifact upload
          docker cp "${CONTAINER_ID}:/app/mcp-starter/logs/." mcp-starter/logs/ || true

          # Inspect container exit code
          EXIT_CODE=$(docker inspect "$CONTAINER_ID" --format='{{.State.ExitCode}}') || true
          echo "Container exit code: $EXIT_CODE"
          docker rm "$CONTAINER_ID" >/dev/null || true
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "Container exited with code $EXIT_CODE"
            exit $EXIT_CODE
          fi

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-logs
          path: mcp-starter/logs/**

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-logs-all
          path: mcp-starter/logs/**
